### PR TITLE
New Timer and StageDisplay Features

### PR DESCRIPTION
**Pull request by greyshirtguy**
Added new dynamic variables:
* current_stage_display_name: (The name of active stage display layout - updated when changed)
* current_stage_display_index: (The index of active stage display layout - updated when changed)
* watched_clock_current_time: (The current value of a clock/timer that is selected in the module config. In the Pro6 module config, you can now specify the index of a clock you wish to keep track of and this dynamic variable will be updated once per second)

Added new action "Toggle Stage Display Layout" - You can specify two Stage Display Layouts (by index) and the action will toggle back and forth between them. (It's nice to put the current_stage_display_name on this button title).

Made getProPresenterState more efficient by updating the 'presentationCurrent' action to include presentationSlideQuality: 0 attribute. Setting presentationSlideQuality to 0 stops Pro6 from including the slide preview image data (which is a lot of data) - no need to get slide preview images since we are not using them!

### CODE REVIEW

**Comment by SteveTherrien** [comment]
Nice work!

Two suggestions:
- Could you update your code style to match the [Module Development](https://github.com/bitfocus/companion/wiki/Module-Development#bracing-and-indentation) guide?
  - Specifically the bracing on lines 588-591 and 715/716 are missing opening and closing `{ }`
  - A space between `if` and `(self.currentState` on line 772
- Could you update HELP.md to describe the new actions and dynamic variables?

Thanks

**Comment by greyshirtguy** [comment]
Oh - my bad!  I will fix up the style to match the guide I, ahem, should have read!

**Comment by greyshirtguy** [comment]
All done!

**Comment by SteveTherrien** [comment]
Almost there :)

Remove the newline after `}` on line 589. It should look like this:

```
		case 'stageDisplayToggle':
			var newStageDisplayIndex = opt.index1;
			if (self.currentState.internal.slideIndex == opt.index1) {
				newStageDisplayIndex = opt.index2;
			} else {
				newStageDisplayIndex = opt.index1;
			}
```

You should add a regex on the `indexOfClockToWatch` config field (`REGEX_NUMBER`).

The regex used on the `stageDisplayLayout`, `stageDisplayToggle`, and all the clock actions should be `REGEX_NUMBER` and not `REGEX_SIGNED_NUMBER` (which accepts signed integers like `-3` or `+5`). It's only that way on the `slideNumber` action because relative numbers are allowed there (line 518).

**Comment by SteveTherrien** [comment]
Nice

One last thing, why add a `Toggle Stage Display Layout` action instead of using latch/toggle with the existing `Stage Display Layout` action?

This setup acts the same:

latch

Maybe we could drop this new action and instead add a [Preset](https://github.com/bitfocus/companion/blob/master/documentation/gettingstarted.md#presets) to simplify the creating of a toggle stage display button. It looks like the [presets development documentation](https://github.com/bitfocus/companion/wiki/Module-Development#presets) needs a bit of work, but you should be able to work it out using the [bmd-multiview4 module](https://github.com/bitfocus/companion-module-bmd-multiview4/blob/master/index.js#L96) as an example.

**Comment by greyshirtguy** [comment]
Face-palm!
Well that's one way for me to learn about feature I didn't realise was there!
No need for the toggle action! I'll remove it and look into creating a preset (or two)

**Comment by greyshirtguy** [comment]
Toggle Stage Display Layout is removed in lieu of using latched  button with two Set Stage Display Layouts. (I did notice one corner case where an extra button press is required to toggle the layout - but it's not too big of a deal).

I also added some presets!

**Comment by SteveTherrien** [comment]
Looks good to me 👍

**Comment by KDLN** [comment]
This is great! Is there a way to let it set specific times ie 7am 8:30pm etc? not just 10min, 20min?

**Comment by greyshirtguy** [comment]
Not yet - should be easy enough to add...
It's on the TODO list...
I'll add that someone in the next week or so to my forked code...and hopefully it's get accepted and merged soon after that.
I'm not that fast....and I personally needed countdowns first ;)

**Comment by willosof** [comment]
Nice..

**Comment by cxselph** [comment]
I tried the new timer addons today and love it. After playing with it a while I thought it would be handy to have the show and hide actions. Show when you start your countdown and hide when you reset. That will let you run without having the Propresenter computer in front of you. Thanks for the great additions to this module!

**Comment by greyshirtguy** [comment]
cxselph: I'm a little slow....hopefully you can help me. I'm not sure exactly what you mean with the "Show and Hide Options", do you mean show/hide messages (that might contain timers) and are displayed on the main output?
Or do you mean to show/hide the timers on the stage display? (which would be done by changing stage display layout)

**Comment by cxselph** [comment]
Yes. The show/hide messages that contain timers.
screen shot 2019-02-06 at 9 34 08 pm

**Comment by greyshirtguy** [comment]
I'll add that soon! ;)

**Comment by cxselph** [comment]
Thanks! That will make timers for special events so much easier.

**Comment by greyshirtguy** [comment]
Okay here are the notes for next version. (over the next few weeks)
* Add the two other clock types ("countdown to time" and "elapsed time")
* Show & Hide Message actions
* Start Audio Cue action
* Audio Play & Pause actions

**Comment by JeffreyDavidsz** [comment]
Keep up the good work guys!

**Pull request merged**
