### PR TITLE
Alternative labels for countdown clock presets for when indexOfClockToWatch is undefined

### PR DESCRIPTION
**Pull request by justingiffard**
Give alternative labels for countdown clock presets for when `indexOfClockToWatch` is `undefined`

When you first add an instance of ProPresenter to Companion, if you don't restart Companion before adding a preset button self.config.indexOfClockToWatch is undefined

With this fix, for the first preset instead of "Clock \n undefined \n 5 mins" It now says "Clock \n 5 mins"
For the other three presets (Start, Stop, Reset) instead of "Start \n Clock \n undefined" it says "Start \n\n 00:00:00"

After resetting Companion the the presets will look exactly as they did before this change

### CODE REVIEW

**Comment by justingiffard** [comment]
When self.config.indexOfClockToWatch is undefined 

undefined

When self.config.indexOfClockToWatch has a value

hasValue

**Comment by justingiffard** [comment]
Any chance you could label this PR as "hacktoberfest-accepted"? I saved this fix (amongst others) for this month so that it can contribute to my Hacktoberfest counter but apparently either the repository needs to have "hacktoberfest" in its topic or the individual PR needs to be labeled as above.

**Comment by greyshirtguy** [comment]
Thanks for the fix! - I hadn't noticed that issue.
What do you think about just defaulting indexofclocktowatch to 0 instead???

**Comment by justingiffard** [comment]
> Thanks for the fix! - I hadn't noticed that issue.
> What do you think about just defaulting indexofclocktowatch to 0 instead???

Tried that but then at same time you don't know what the user has set when they configured the instance (maybe they set it to 2 and the user experience wont be great if it defaults to 0 and they have chosen 2

**Comment by greyshirtguy** [comment]
Good point - currently the code only updates presets at module load..
A single line fix to all of this would be to call self.init_presets(); inside instance.prototype.updateConfig = function(config) {
It's still not perfect as the presets don't update until you refresh them - but this feels to me like fixing the root issue.
What do you think?

**Comment by greyshirtguy** [comment]
I do kinda prefer this one-liner fix mentioned in previous comment - it feels more like _addressing_ the issue (rather than _working around_ it)...Also, there is no longer a need to reload module.....Do you think I am missing something?
I know the refresh is required to see the presets change (ie, just leave presets and re-visit them).....but this would be true of your pull request as well.
If you agree - happy for you to submit PR and get your hacktober-thingy hit.
If you see something wrong with my logic/thinking then please let me know!!!

**Comment by greyshirtguy** [comment]
image

**Comment by justingiffard** [comment]
@greyshirtguy, just tested and that does indeed work, would you like me to change it in this PR?

On a somewhat unrelated note can I try add a default port for when adding an instance? So if the user doesn't type anything in the port field it will default to 20652 when they click "Apply changes" but if they do enter a port it will use that one (not sure if Companion will currently allow that but I can try

**Review by greyshirtguy — APPROVED** [review]

**Comment by justingiffard** [comment]
@greyshirtguy any chance you can label this PR as "hacktoberfest-accepted"?

**Comment by justingiffard** [comment]
@greyshirtguy any chance you can label this PR as "hacktoberfest-accepted"?

**Comment by justingiffard** [comment]
@greyshirtguy can you please label this PR as "hacktoberfest-accepted" as you promised?

**Pull request merged**
